### ISSUE TITLE
Number.isNaN undefined on iOS?

### ISSUE THREAD

**Issue by mdsib** [lifegadget/ui-slider#1]
During `initializeJqueryComponent` ui-slider fails to load because Number.isNaN isn't a function. This could be an iOS specific issue, or could be more widespread. This could also be a function of using an outdated version of Ember CLI that doesn't correctly transpile Number.isNaN.

**Comment by ksnyde** [comment]
Hmmm. What version of Babel are you using? 

`Number.isNan` is an ES6 version if `isNan` so that might be the issue although possibly this function requires the runtime transpiler which would be annoying. One way to test this quickly would be to test your app on a desktop browser.

**Comment by mdsib** [comment]
I'm using Babel 5.0.0

It looks like Babel's polyfill script is required to ensure this works on all browsers, since most mobile browsers and IE haven't implemented this yet.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

We can either destroy ui-slider's dependency on the polyfill or make the polyfill an official dependency.

**Comment by ksnyde** [comment]
I'd prefer avoiding the dependency in this case. Should be easy enough to move away from.

**Comment by ksnyde** [comment]
I've removed the dependency in `0.1.2`.
