### ISSUE TITLE
_immediateResponse instantiates before _slider exists in some cases

### ISSUE THREAD

**Issue by mdsib** [lifegadget/ui-slider#2]
`initializeJqueryComponent` is ran during the `afterRender` phase of the Ember Run loop, where `_slider` is instantiated. However, `_slider` is expected to exist when the `_immediateResponse` method is called after the element is inserted into the DOM, which is before the rendering has completed.

I was getting an error until I scheduled `_immediateResonse`'s body in the afterRender phase as well.

**Comment by ksnyde** [comment]
this should now be fixed in the `v0.1.2`. I'll close it for now but if you're still having problems with it just re-open.

**Comment by mdsib** [comment]
Cool, thanks!
