### ISSUE TITLE
immediateResponse observer not triggered

### ISSUE THREAD

**Issue by janmisek** [lifegadget/ui-slider#5]
Nice addon thanks.

But immediateResponse does not work because observer is not triggered during definition of component. Ember components are not by default triggered during object init.

This currently does not work
```
# template.hbs
            {{ui-slider
            ticksSnapBounds=50
            tooltip='show'
            tooltipPosition='bottom'
            value=zoom
            min=zoomMin
            max=zoomMax
            immediateResponse=true
            }}
```

However this simple workaround works

```
# template.hbs
            {{ui-slider
            ticksSnapBounds=50
            tooltip='show'
            tooltipPosition='bottom'
            value=zoom
            min=zoomMin
            max=zoomMax
            immediateResponse=immediateResponse
            }}
```

```
# component.js

        didInsertElement: function() {
            Ember.run.later(function() {
                this.set('immediateResponse', true);
            }.bind(this));
        },
```

**Comment by ksnyde** [comment]
Strange. It works fine on the demo app. Out of interest what version of Ember are you using?

**Comment by ksnyde** [comment]
I'm away from my computer until tomorrow, I'll probably have a quick look at this then if you're still experiencing this.

**Comment by ksnyde** [comment]
Actually just looked at the code on my phone ... It's a one line change. I'll make the change tomorrow as I don't believe in "phone coding". :)

**Comment by ksnyde** [comment]
this should now be fixed (v.0.1.3); please re-open it if it is not

**Comment by janmisek** [comment]
Hello @ksnyde I will check soon. Thanks for quick response. 

Regards Jan
