### ISSUE TITLE
Cannot install version 0.1.3

### ISSUE THREAD

**Issue by janmisek** [lifegadget/ui-slider#6]
Hello

when version 0.1.3 is installed I am getting following exception on ember-cli command line:

```
The package `ui-ember-slider` is not a properly formatted package, we have used a fallback lookup to resolve it at `/www/themeeditor/node_modules/ui-ember-slider`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
The `ui-ember-slider` addon could not be found at `/www/themeeditor/node_modules/ui-ember-slider`.
```

version 0.1.2 works just fine.

#5 

Thanks

**Comment by ksnyde** [comment]
Bizarre. I just installed it without issue. I'd say just do a `npm cache clear && rm -rf node_modules` and then `npm install` it all back. Let me know if that works.

**Comment by ksnyde** [comment]
btw, there is a well known npm problem where if you don't specify both `main` and `files` in the package file you'll get very inconsistent behaviour but I just checked and that's already been done here.

**Comment by janmisek** [comment]
Ok I will check myself and produce pr

**Comment by ksnyde** [comment]
I just found this same error in another plugin of mine. Installing with `npm` works with no issue and `ember install` does install the npm module but falls over on the bower dependency. I've made some very small changes and I think `0.1.4` should work for you (did for me).

**Comment by janmisek** [comment]
Thanks for reply and fix. I have to work on another project now so i am unable to check currently. I will let you know asap.

**Comment by ksnyde** [comment]
Ok, i'll close for now but reopen it if you find you're still having this problem.
