### ISSUE TITLE
willDestroyElement is called twice

### ISSUE THREAD

**Issue by mrDoktar** [lifegadget/ui-slider#7]
Using the ui-slider component and transitioning to a new route causes the willDestroyElement to be called twice. Once directly and once through the event listener.

To fix this one can either remove: 
https://github.com/lifegadget/ui-slider/blob/master/addon/components/ui-slider.js#L314

    _d: on('willDestroyElement', function() { return this.willDestroyElement(); }),

or rename
https://github.com/lifegadget/ui-slider/blob/master/addon/components/ui-slider.js#L332

    willDestroyElement: function() { ... }

to something else (and also renaming it in the event listener on line 314).
Example:

    _d: on('willDestroyElement', function() { return this.willDestroyElementOnce(); }),
    willDestroyElementOnce: function() { ... }

**Comment by mrDoktar** [comment]
Using emberjs 2.0

**Comment by ksnyde** [comment]
Ahh thanks. Will get this fixed today.

**Comment by ksnyde** [comment]
@mrDoktar try out npm `0.1.15` ... the problem should be fixed there. I'll close this for now but please reopen if you're still having issues.
